### ISSUE TITLE
tested? are my bookmarks safe?

### ISSUE THREAD

**Issue by KeLaiFu** [devec0/uruz-busboard#1]
This looks like the mother of all bus boards, has it been tested?

**Comment by digitalrane** [comment]
Yes, I've been using two of these busboards for a couple of years without any issues.
But as usual, the normal warranty applies -
 * These busboards will destroy all of your synth modules
 * These busboards will destroy your house
 * These busboards will destroy your village
Because of these facts, there is no guarantee or warranty they are fit for any purpose.
